[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.devnet]
nyxbid = "nyxkGtm8x7GMdTWKyy5TKa72pgsebrECrchPDuRSrEQ"

[programs.localnet]
nyxbid = "nyxkGtm8x7GMdTWKyy5TKa72pgsebrECrchPDuRSrEQ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run test"

[hooks]
