[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.devnet]
nyxbid = "E9sMPu6uUJTfe72ePWr8BNjEKejUnMqsdFV6rGtsHiX2"

[programs.localnet]
nyxbid = "E9sMPu6uUJTfe72ePWr8BNjEKejUnMqsdFV6rGtsHiX2"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
